# Application variables
my_app_name: my-app
my_app_port: 8080
my_app_dir: /home/marzena/my_app
my_app_github_repo: https://github.com/MazPugo/my_app.git
my_app_domain: myappguru.net
my_app_docker_image: my_app

# Firewall ports
allowed_ports:
  - "22"
  - "80"
  - "443"

# Reference vault variables
secret_key: "{{ vault_secret_key }}"
